language: scala
dist: xenial

scala:
  - 2.12.10
  - 2.13.1

script:
  - ./millw _[$TRAVIS_SCALA_VERSION].test

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.mill/download

jdk:
  - openjdk8

branches:
  only:
  - master
