language: scala
dist: xenial

scala:
  - 2.12.11
  - 2.13.2

script:
  - ./millw _[$TRAVIS_SCALA_VERSION]._.test

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.mill/download

jdk:
  - openjdk8

branches:
  only:
  - master
